### PR TITLE
fix: import failure on Python >=3.10

### LINKED ISSUE #91: ImportError: cannot import name Iterable from collections on Python 3.10
It just doesn't work. It expects Iterable from collections but this is not available.

This log is from building `python310Packages.fn` with nix but should be reproducible on any python 3.10 out there
```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/bhfhqwy9y6x63h4dq2lpimzkl0b2b29i-fn-0.4.3.tar.gz
source root is fn-0.4.3
setting SOURCE_DATE_EPOCH to timestamp 1407495729 of file fn-0.4.3/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "/build/fn-0.4.3/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 6, in <module>
    import fn
  File "/build/fn-0.4.3/fn/__init__.py", line 1, in <module>
    from .stream import Stream
  File "/build/fn-0.4.3/fn/stream.py", line 9, in <module>
    from .iters import map, range
  File "/build/fn-0.4.3/fn/iters.py", line 2, in <module>
    from collections import deque, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/nix/store/443qk9752l44kfp8pzsrp0m9jyq6jz2p-python3-3.10.3/lib/python3.10/collections/__init__.py)

```

Backlinks: https://github.com/NixOS/nixpkgs/pull/167402

### PR DESCRIPTION
**Pull request by lucasew**
My worry is that this breaks backward compatibility because the `typing` module was added on Python 3.5 [1], so it would only work on Python 3.5 and above.

We realized this because the nixpkgs CI [2] fails to package this library to be used by other dependents. It's not that a huge problem because basically all of the stuff depends on the version based on Python 3.9, that works fine [3].

[1] https://docs.python.org/3/library/typing.html

[2] https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.fn.x86_64-linux

[3] https://hydra.nixos.org/job/nixpkgs/trunk/python39Packages.fn.x86_64-linux

Closes https://github.com/kachayev/fn.py/issues/91 https://github.com/kachayev/fn.py/issues/86

### CODE REVIEW

**Comment by ftsfranklin** [comment]
Duplicate of #87, which has better compatibility.

`typing.Iterable` is just a generic fork of `collections.abc.Iterable`, and [was deprecated in 3.9](https://docs.python.org/3.9/library/typing.html#typing.Iterable).

This one should work for newer Python versions, while not breaking compatibility with older ones:
```py3
try:
    from collections.abc import Iterable
except ImportError:  # py < 3.3
    from collections import Iterable
```
